### ISSUE TITLE
能否加入浅色皮肤?

### ISSUE THREAD

**Issue by Renkai** [pingshunhuangalex/rime-xkjd-docs#3]
作者你好!
我很有兴趣学习文档内容, 可是这份gitbook在我的显示器上效果不佳, 能否加入浅色皮肤选项?

**Comment by pingshunhuangalex** [comment]
你好 @Renkai 

目前Gitbook提供的API中只能从浅色和深色模式中选择一种。

能否详细说一下具体哪里显示不佳，也许我可以做出一些调整。

如果实在是无法解决，我可以把文档切换到浅色模式。谢谢。

**Comment by Renkai** [comment]
应该是我显示器本身的问题为主, 浏览互联网上大部份深色文档效果都不佳, 所以我会在有得选的情况下调成浅色.

**Comment by pingshunhuangalex** [comment]
我个人感觉深色模式显示效果更好，但是文档使用者优先吧。
已切换为浅色模式了。
