### ISSUE TITLE
关于用户自造词功能的说明

### ISSUE THREAD

**Issue by Renkai** [pingshunhuangalex/rime-xkjd-docs#4]
我在一篇[知乎文章](https://zhuanlan.zhihu.com/p/456173479)看到，可以使用a开头触发自造词。可是我自己试了没用（对应平台为Mac Squirrel），请问这项功能是否在不同平台有所差异？

**Comment by pingshunhuangalex** [comment]
这项功能应该是这个用户自己魔改的（他用的是`Rime唯一自动上屏`来进行覆盖安装）。文章中提到的u模式、v模式以及农历日期也是用户自己添加的。如果你有兴趣可以在星空QQ大群的网盘里找一下或者直接联系作者。

官方键道和`我流`都不包含自动造词功能。其原因是键道词库对候选项的顺序以及重码的处理有较高的要求。自动造词所产生的用户词典无法准确的根据形码在现有词库中进行穿插。虽然也能通过`shift+方向键`进行微调，但是光看候选项是无法有效进行排序的（更不要说`我流`是盲打，是没有候选项菜单的）。除开没有一个特定的图形界面以外，用户自己进词库文件进行编辑实际上效率要高得多。
